#========================
# SERVER PORT NUMBER
#========================

server:
  port: 9889

# ===============================
# JPA / HIBERNATE
# =============================== 
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 
    
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        
#===================================
# ORACLE DATABASE PROPETIES  
#===================================     
  datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver       
        url: jdbc:oracle:thin:@localhost:1521:xe
        username: SYSTEM
        password: MANAGER
       
# ===============================
# JSP CONFIGURATION
# ===============================
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp